H_Management/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include
urlpatterns = [
    path('resetpassword', PasswordResetView.as_view(), name='password_reset'),
    path('resetpassword/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('resetpassword/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('resetpassword/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('', include('hostel.urls')),
]

hostel/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from . import views
from hostel.admin import user_admin_site

app_name = 'hostel'

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('login', views.signin, name='login'),
    path('register', views.reg, name='reg'),
    path('user/', views.open_dashboard_view, name='dashboard'),
    path('', views.home, name='home'),
    path('verification/<username>/<uid>', views.verification_view, name='verification'),
    path('changepassword', views.change_password, name='changepassword'),
    path('postlogin', views.postlogin, name='postlogin'),
    path('logout', views.logout_view, name='logout'),
    path('user-admin', user_admin_site.urls, name='admin_login'),
    path('update',views.update,name='update'),

]

hostel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from enum import Enum


class Person(models.Model):

    GENDER = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('o', 'Other'),
    )

    user = models.OneToOneField(User, default=None, on_delete=models.CASCADE, related_name='userProfile')
    person_is_warden = models.BooleanField(default=False)
    person_phone = PhoneNumberField(null=False, blank=False, unique=True)
    person_prn = models.CharField(max_length=150, unique=True, null=False, default='0')
    person_room_number = models.CharField(max_length=15, null=True, default='0')
    person_is_chief = models.BooleanField(default=False)
    UID = models.CharField(max_length=32,default='')
    isVerified = models.BooleanField(default=False)
    person_gender = models.CharField(
        max_length=2,
        choices=GENDER,
    )

    def __str__(self):
        if self.person_gender == 'M':
            gen = "Mr."
        elif self.person_gender == 'F':
            gen = "Miss "
        else:
            gen = ' '

        return gen + self.user.get_full_name()


class Complaint(models.Model):
    TYPE = (
        ('room', 'Room'),
        ('wifi', 'WiFi'),
        ('water', 'Water'),
        ('other', 'Other'),
    )

    class Status(Enum):
        Registered = 'reg'
        In_Process = 'in_process'
        Solved = 'solved'

    STATUS = (
        ('reg', 'Registered'),
        ('ip', 'In process'),
        ('s', 'Solved'),
    )

    complaint = models.CharField(max_length=200)
    reg_by = models.ForeignKey(Person, on_delete=models.CASCADE)
    complaint_type = models.CharField(
        max_length=10,
        choices=TYPE,
    )
    complaint_status = models.CharField(
        max_length=10,
        choices=STATUS,
    )

    def __str__(self):
        return 'Complaint number' + str(self.id) + ' by ' + self.reg_by.user.last_name


class MessMenu(models.Model):
    DAY = (
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    )

    day_day = models.CharField(
        max_length=10,
        choices=DAY,
        unique=True
    )

    soup = models.CharField(max_length=50)
    main_course = models.CharField(max_length=100)
    dessert = models.CharField(max_length=50)

    def __str__(self):
        return self.get_day_day_display()

hostel/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from .models import Person
from phonenumber_field.modelfields import PhoneNumberField
from django import forms


class UserLogin(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control'
        }
    ))

    class Meta:
        model = User
        fields = ['email', 'password']


class RegForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100, widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)
    # retype_password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(max_length=100)
    gender = forms.ChoiceField(choices=Person.GENDER)
    prn = forms.CharField(max_length=20)
    room_number = forms.IntegerField(max_value=10)

    class Meta:
        model = Person
        fields = [
            'first_name', 'last_name', 'email', 'password', 'phone', 'gender', 'prn', 'room_number'
        ]


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]

hostel/views.py
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.core.mail import send_mail
from django.forms import model_to_dict
from django.http import Http404
from django.utils.crypto import get_random_string

from .models import Person
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, update_session_auth_hash, logout
from django.contrib.auth.models import auth
from django.urls import reverse_lazy
from django.views.generic import View
from django.views import generic
from .forms import UserLogin, RegForm, EditProfileForm
from .models import Person
from H_Management.settings import EMAIL_HOST_USER


def welcome(request):
    return render(request, 'hostel/welcome.html', None)


class Login(View):
    form_class = UserLogin
    template_name = 'hostel/userLogin.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'UserForm': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # user = form.save(commit=False)
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = authenticate(email=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('hostel:welcome')

        return render(request, self.template_name, {'form': form})


def reg(request):
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            phone = form.cleaned_data['phone']
            gender = form.cleaned_data['gender']
            prn = form.cleaned_data['prn']

            cu = User.objects.values_list('email')
            for em in cu:
                if email == em:
                    return redirect('hostel:reg')
            cu = User.objects.values_list('username')
            for em in cu:
                if email == em:
                    return redirect('hostel:reg')
            uid = get_random_string(length=32)

            p = Person()
            p.person_phone = phone
            p.gender = gender
            p.person_prn = prn
            p.UID = uid
            message = "hostelmanagerintern.herokuapp.com/verification/" + str(form.cleaned_data['email']) + "/" + uid
            send_mail("Verification/", message, EMAIL_HOST_USER, [form.cleaned_data['email']], fail_silently=False)

            us = User()
            us.first_name = first_name
            us.last_name = last_name
            us.email = email
            us.username = email
            us.set_password(password)
            p.user = us
            us.save()
            p.save()
            return redirect('hostel:login')
    else:
        form = RegForm()

    return render(request, 'hostel/reg_student.html', {'form': form})


def signin(request):
    print(request.method)
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        print(username, " ", password, " ", user)
        if user is not None:
            if user.userProfile.isVerified:
                auth.login(request, user)
                return redirect('hostel:dashboard')
            else:
                messages.error(request, 'Please Verify your email first...!!')
                return redirect('hostel:login')
        else:
            messages.error(request, 'Invalid email or password')
            return redirect('hostel:login')
    else:
        return render(request, 'hostel/login.html')


def open_dashboard_view(request):
    user_id = request.user.id
    userprofile = get_object_or_404(Person, user_id=user_id)
    user = get_object_or_404(User, id=user_id)

    context = {
        'user': user,
        'userprofile': userprofile
    }
    return render(request, 'hostel/dashboard.html', context)


def home(request):
    return render(request, "hostel/index.html")


def verification_view(request, username, uid):
    user = User.objects.get(username=username)
    if user:
        if user.userProfile.UID == uid:
            print(user.userProfile.isVerified)
            user.userProfile.isVerified = True
            user.userProfile.save()
            print(user.userProfile.isVerified)
            return redirect('hostel:login')
    raise Http404("Not Verified")


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()

            """Rehashing of password is done using update_session_auth_hash"""

            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('hostel:dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'hostel/changepassword.html', {
        'form': form
    })


def postlogin(request):
    user = request.user
    print(user.email)
    userprofile = model_to_dict(user.user_profile)
    user = model_to_dict(user)
    return render(request, 'hostel/dashboard.html', {'user': user, 'userprofile': userprofile})


def logout_view(request):
    logout(request)
    return render(request, 'hostel/login.html')


def update(request):
    user = get_object_or_404(User, id=request.user.id)
    userprofile = get_object_or_404(Person, user_id=request.user.id)
    form = RegForm(request.POST or None, instance=userprofile)
    form1 = EditProfileForm(request.POST or None, instance=user)
    # print('FORM!!!!!!!!!!!!!!!!!!',form)
    if request.method == 'POST':
        print('i am here')
    if form.is_valid() and form1.is_valid():
        print('goodbye')
        user = form1.save()
        profile = form.save(commit=False)
        profile.user = user
        profile.save()
        return redirect('postlogin')
    else:
        print(form.errors, form1.errors)
    return render(request, 'hostel/update.html', {
        'form': form,
        'form1': form1
    })

templates/hostel/changepassword.html
{% extends "hostel/dashboard.html" %}
{%block nav-home%}
<style>
    input {
        background-color: #e0e0e0;
    }

    .submitbtn {
        font-size: 14px;
        font-weight: 650;
        color: white;
        text-align: center;
        padding: 6px 25px 0px 20px;
        display: inline-block;
        text-decoration: none;
        width: 250px;
        height: 35px;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        background-color: #1def45;
        -webkit-box-shadow: 0 3px #4eb145;
        -moz-box-shadow: 0 3px #4eb144;
        box-shadow: 0 3px #4eb14e;
        transition: all 0.1s linear 0s;
        top: 0px;
        margin-left: 15px;
        margin-top: 30px;
        margin-bottom: 50px;
    }

    .submitbtn:hover {
        top: 3px;
        background-color: #1de21d;
        -webkit-box-shadow: none;
        -moz-box-shadow: none;
        box-shadow: none;
        text-decoration: underline;
    }
</style>
<li>
    <a href="{%url 'hostel:postlogin'%}"><span class="fa fa-home mr-3"></span> Homepage</a>
</li>
{%endblock%}
{%block nav-changepassword%}
<li class="active">
    <a href="{%url 'hostel:changepassword'%}"><span class="fa fa-sticky-note mr-3"></span> change password</a>
</li>
{%endblock%}

{%block content%}
<div>
    <form action="" method="post">
        {%csrf_token%}
        <p><h5><b>Old password:</b></h5> {{form.old_password}}</br></p>
        <hr>
        <p><h5><b>new Password:</b></h5> {{form.new_password1}}</br></p>
        <hr>
        <p><h5><b>Confirm password:</b></h5> {{form.new_password2}}</br></p>
        <hr>
        <p>{{form.errors}}</p>

        <p>
            <button class="submitbtn" type="Submit" >Submit</button>
        </p>
    </form>

</div>
{%endblock%}

templates/hostel/dashboard.html
<!doctype html>
{%load static%}
<html lang="en">
<head>
    <title>Dashboard</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'sidebar/css/style.css'%}">
</head>
<body>

<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
        <div class="custom-menu">
            <button type="but+ton" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only">Toggle Menu</span>
            </button>
        </div>
        <h1><a href="index.html" class="logo">Dashboard</a></h1>
        {%block nav%}
        <ul class="list-unstyled components mb-5">
            {%block nav-home%}
            <li class="active">
                <a href="#"><span class="fa fa-home mr-3"></span> Homepage</a>
            </li>
            {%endblock%}

            {%block nav-friends%}
            <li>
                <a href="{%url 'hostel:logout'%}"><span class="fa fa-power-off mr-3"></span> Logout</a>
            </li>
            {%endblock%}
            {%block nav-changepassword%}
            <li>
                <a href="{%url 'hostel:changepassword'%}"><span class="fa fa-lock mr-3"></span>Change Password</a>
            </li>
            {%endblock%}
<!--            {%block nav-dashboard%}-->
<!--            <li>-->
<!--                <a href="{%url 'hostel:update'%}"><span class="fa fa-upload mr-3"></span>Update Profile</a>-->
<!--            </li>-->
<!--            {%endblock%}-->
        </ul>
        {% endblock %}
    </nav>

    <!-- Page Content  -->

    <div id="content" class="p-4 p-md-5 pt-5">
        {%block header%}<h3 class="mb-4"><i>HELLO <b><u style="font-size: 24px">&nbsp;&nbsp;  {{user.username}}</u></b>
    </h3></i>{%endblock%}
        {%block content%}
        <div class="testbox">
            <b>First Name :</b><br>
            <h4>{{user.first_name}}</h4>
            <hr>
            <b>Last Name : </b><br>
            <h4>{{user.last_name}}</h4>
            <hr>
            <!--<b>Gender : </b><br>
            <h4>{{userprofile.person_gender}}</h4>
            <hr>-->
            <b>Email : </b><br>
            <h4>{{user.username}}</h4>
            <hr>
            <b>Phone Number : </b><br>
            <h4>{{userprofile.person_phone}}</h4>
            <hr>
            <b>PRN : </b><br>
            <h4>{{userprofile.person_prn}}</h4>
            <hr>
            <b>Room Number : </b><br>
            <h4>{{userprofile.person_room_number}}</h4>
            <hr>
        </div>
        {%endblock%}
    </div>

</div>

<script src="{% static 'sidebar/js/jquery.min.js' %}"></script>
<script src="{% static 'sidebar/js/popper.js' %}"></script>
<script src="{% static 'sidebar/js/bootstrap.min.js' %}"></script>
<script src="{% static 'sidebar/js/main.js' %}"></script>
</body>

<style>
    .testbox {
        margin-left: 15px;
        margin-top: 10px;
    }

    hr {
        color: #a9a9a9;
        opacity: 0.3;
    }

    b {
        text-transform: uppercase;
        color: #000000;
        font-size: 18px;
        font-weight: 800;
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }


</style>
</html>

templates/hostel/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/hostel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% load static %}

</head>
<body style="background-image:url('{% static 'images/background.jpg'%}')">

<nav class="navbar navbar-expand-sm fixed-top navbar-light">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'hostel:home' %}"><span class="glyphicon glyphicon-home"
                                                                           aria-hidden="true"></span>&nbsp; Home</a>
                </li>
                <li><a href="{% url 'hostel:reg' %}"><span class="glyphicon glyphicon-registration-mark"
                                                           aria-hidden="true"></span>&nbsp; Register</a></li>
                <li><a href="user-admin"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Admin Login</a>


            </ul>
        </div>
    </div>
</nav>

<section id="welcome">
    <div class="welcome-container">
        <h1><em>Welcome</em><br></h1>
        <a href="{% url 'hostel:login' %}" class="btn-get-started">Explore</a>
    </div>
</section>


<style>

    .container-fluid {
        background: transparent;
    }

    #myNavbar {
        color: #000000;
    }

    #welcome {
        text-align: center;
        text-decoration-style: double;
        margin-top: 15%;
        vertical-align: middle;
    }

    li:hover {
        text-decoration: underline;
        font-size: 16px;
    }

    h1 {
        font-weight: 900;
        text-transform: uppercase;
    }

    body {
        background-size: 100%;
        background-attachment: fixed;
        background-repeat: no-repeat;

    }

    b {
        text-transform: uppercase;
        color: #000000;
        font-weight: 800;
        font-family: cursive, fantasy, 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }

    em {
        font-weight: 900;
    }

    a {
        text-decoration: none;
        color: #000000;
    }

    a:hover {
        text-decoration: none;
        color: #000000;;
    }

    a.btn-get-started {
        font-family: "Poppins", Georgia, 'Times New Roman', Times, serif;
        text-transform: uppercase;
        font-weight: 550;
        font-size: 16px;
        letter-spacing: 1px;
        display: inline-block;
        padding: 8px 28px;
        border-radius: 50px;
        transition: 0.5s;
        margin: 10px;
        border: 2px solid #b3b1b1;
        color: black;
        text-decoration: none;
    }
</style>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/hostel/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<h2>Hello {{user}}</h2>
<p>Email : {{user.email}}</p>
</body>
</html>

templates/hostel/reg_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration page</title>

    {%  load static %}
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'css/main.css'%}">

</head>

<body style="background-image:url('{% static 'images/background.jpg'%}')">

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-body">
                <h1>Registeration</h1>
                <hr><hr>
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {% include 'hostel/form-template.html' %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                     <p>Already a user ? <a href="{% url 'hostel:login' %}"> Go Back</a></p>
<!--                    <p>Already a user ? <a href="userLogin.html"> Go Back</a></p>-->

                </form>
            </div>
        </div>
    </div>
</div>
</body>
<style>

.panel-body{
align-content: center;
 margin: 20px auto;
  width: 360px;
  height: 780px;
  -webkit-border-radius: 8px/7px;
  -moz-border-radius: 8px/7px;
  border-radius: 8px/7px;
  /* background-color: #ebebeb;  */
  -webkit-box-shadow: 1px 2px 5px rgba(0,0,0,.31);
  -moz-box-shadow: 1px 2px 5px rgba(0,0,0,.31);
  box-shadow: 1px 1px 4px rgba(0,0,0,.31);
  border: solid 1px #cbc9c9;
  background-color:#FFFFFF;
}
#id_email,#id_password#id_email,#id_password,#id_first_name,#id_last_name,#id_gender,#id_phone,#id_prn,#id_room_number{
  width: 320px;
  height: 30px;
  -webkit-border-radius: 0px 4px 4px 0px/5px 5px 4px 4px;
  -moz-border-radius: 0px 4px 4px 0px/0px 0px 4px 4px;
  border-radius: 0px 4px 4px 0px/5px 5px 4px 4px;
  background-color: #fff;
  -webkit-box-shadow: 1px 2px 5px rgba(0,0,0,.09);
  -moz-box-shadow: 1px 2px 5px rgba(0,0,0,.09);
  box-shadow: 1px 2px 5px rgba(0,0,0,.09);
  border: solid 1px #cbc9c9;
  margin-left: 15px;
  margin-top: 9px;
  margin-bottom:3px;
  padding-left: 10px;
}
button{
font-size: 14px;
  font-weight: 650;
  color: white;
  text-align: center;
  padding: 6px 25px 0px 20px;
  display: inline-block;
  float: none;
  text-decoration: none;
  width: 320px;
  height: 35px;
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
  background-color: #000000;
  -webkit-box-shadow: 0 3px #000000;
  -moz-box-shadow: 0 3px #000000;
  box-shadow: 0 3px #000000;
  transition: all 0.1s linear 0s;
  top: 0px;
  position: relative;
  margin-left: 15px;
  margin-top:30px;
  margin-bottom:50px;
}
label{
margin-top:5px;
font-weight:800;
}
</style>

</html>

templates/hostel/update.html
{% extends "hostel/dashboard.html" %}
{%block nav-home%}
<li>
    <a href="{%url 'hostel:postlogin'%}"><span class="fa fa-home mr-3"></span> Homepage</a>
</li>
{%endblock%}
{%block nav-dashboard%}
<li class="active">
    <a href="{%url 'hostel:update' %}"><span class="fa fa-user mr-3"></span> Dashboard</a>
</li>
{%endblock%}
{%block header%}
<h2 class="mb-4">UPDATE INFO</h2>
{%endblock%}
{%block content%}
<div>
    <form action="" method="post">
        {%csrf_token%}
        <div class="testbox">
            <b>First Name :</b><br>
            <h4>{{user.first_name}}</h4>
            <hr>
            <b>Last Name : </b><br>
            <h4>{{user.last_name}}</h4>
            <hr>
            <b>Gender : </b><br>
            <h4>{{userprofile.person_gender}}</h4>
            <hr>
            <b>Email : </b><br>
            <h4>{{user.username}}</h4>
            <hr>
            <b>Phone Number : </b><br>
            <h4>{{userprofile.person_phone}}</h4>
            <hr>
            <b>PRN : </b><br>
            <h4>{{userprofile.person_prn}}</h4>
            <hr>
            <b>Room Number : </b><br>
            <h4>{{userprofile.person_room_number}}</h4>
            <hr>
        <p>
            <button class="submitbtn" type="Submit" >Submit</button>
        </p>
    </form>

</div>

<style>

    <style>
    input {
        background-color: #e0e0e0;
    }

    .submitbtn {
        font-size: 14px;
        font-weight: 650;
        color: white;
        text-align: center;
        padding: 6px 25px 0px 20px;
        display: inline-block;
        text-decoration: none;
        width: 250px;
        height: 35px;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        background-color: #1def45;
        -webkit-box-shadow: 0 3px #4eb145;
        -moz-box-shadow: 0 3px #4eb144;
        box-shadow: 0 3px #4eb14e;
        transition: all 0.1s linear 0s;
        top: 0px;
        margin-left: 15px;
        margin-top: 30px;
        margin-bottom: 50px;
    }

    .submitbtn:hover {
        top: 3px;
        background-color: #1de21d;
        -webkit-box-shadow: none;
        -moz-box-shadow: none;
        box-shadow: none;
        text-decoration: underline;
    }
</style>

{%endblock%}

templates/hostel/userLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>

    {% load static %}
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet'
          type='text/css'>

    <link rel="stylesheet" href="{% static 'css/main.css'%}">
</head>

<body style="background-image:url('{% static 'images/background.jpg'%}')">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-body">
                <h1>Login</h1>
                <hr>
                <hr>
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    <br>
                    {% csrf_token %}
                    {% include 'hostel/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                    <p>Don't have an account ? <a href="register"> Register</a></p>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/hostel/welcome.html
<h1>welcome!!!!!!!!</h1>